#ifndef LIBMENSAGO_GLOBAL_H
#define LIBMENSAGO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBMENSAGO_LIBRARY)
#  define LIBMENSAGO_EXPORT Q_DECL_EXPORT
#else
#  define LIBMENSAGO_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBMENSAGO_GLOBAL_H
